# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee2bea7d1524e98b760019ce0b7fc0e569eaaaa4f391e640ce7dc88d11513586b25c070e6d54ccc7fda2b0ec5b292e9514d110ac96d3e742dbaba80f0c7b1c8

test:
  secret_key_base: fdbc591c9036ffe71c3f616aa5b8b500c14d039c9821c76ff3a4d0cfba83e433a3fa9689801a7a7088c984b3f4d82073cf5f69d562c457f6f5677c420efbb3a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
